name: sdk

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdks:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - uses: dtolnay/rust-toolchain@1.90
        with:
          components: rustfmt, clippy

      - name: build codex
        run: cargo build --bin codex
        working-directory: codex-rs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build TypeScript SDK packages
        run: pnpm -r --filter ./sdk/typescript run build

      - name: Build native SDK package
        run: pnpm -r --filter ./sdk/native run build

      - name: Lint TypeScript SDK packages
        run: pnpm -r --filter ./sdk/typescript run lint

      - name: Lint native SDK package
        run: pnpm -r --filter ./sdk/native run lint

      - name: Test TypeScript SDK packages
        run: pnpm -r --filter ./sdk/typescript run test

      - name: Test native SDK package
        run: pnpm -r --filter ./sdk/native run test
